{% set name = "pygeoops" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ???

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - geopandas-base >=0.12.1
    - shapely >=2,<2.1
    - topojson

test:
  imports:
    - pygeoops

about:
  home: https://github.com/pygeoops/pygeoops
  summary: 'Library with some less common or extended spatial functions'
  description: |
    PyGeoOps provides some less common or extended spatial algorithms and utility functions.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://pygeoops.readthedocs.io
  dev_url: https://github.com/pygeoops/pygeoops

extra:
  recipe-maintainers:
    - theroggy
